#!/bin/bash

## Version
wget -O $HOME/LICENSE.txt https://raw.githubusercontent.com/emirjorge/vps/master/LICENSE.txt &> /dev/null
wget -O $HOME/version https://raw.githubusercontent.com/emirjorge/vps/master/version &> /dev/null
wget -O /bin/versao_script https://raw.githubusercontent.com/emirjorge/vps/master/Install/versaoatt &> /dev/null

## Systemverify
rm -rf $HOME/systemverify* &> /dev/null




 
